spring.application.name=ollama-rag-chatbot

# Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.init.pull-model-strategy=when_missing
spring.ai.ollama.init.timeout=5m
spring.ai.ollama.chat.options.model=llama3

# pgvector settings
spring.ai.vectorstore.pgvector.initialize-schema=true

# DataSource for pgvector
spring.datasource.url=jdbc:postgresql://localhost:5432/vectordb
spring.datasource.username=testuser
spring.datasource.password=testpwd

#spring.docker.compose.enabled=false
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

server.tomcat.max-swallow-size=-1

